apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: deepikdc/onmo-sports:975159917a94004e4727d49b95509a6ecfeaa696
          ports:
            - containerPort: 8080
