name: build artifact

on:
  workflow_call

jobs:
  build-artifact:
    runs-on: self-hosted
    steps:
      - name: Build with Maven
        run: mvn clean package
      
      - name: List Target Artifacts
        run: ls -lh target/