name: build and archive artifact local and remote

on:
  workflow_call

jobs:
  build-artifact:
    runs-on: self-hosted
    steps:
      - name: Build with Maven
        run: mvn clean package
      
      - name: List Target Artifacts
        run: ls -lh target/

# archive the artifacts locally 
      - name: Archive Target Artifacts (local directory in runner _work space)
        run: |
          mkdir -p archive
          cp target/*.jar archive/
          echo "Artifacts archived in 'archive' directory."
      
      - name: List Archived Artifacts
        run: ls -lh archive/
        
# archive the artifacts remotely in github

      - name: Archive JAR from target directory (github remote artifact)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/*.jar        