name: Modular CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: ./.github/workflows/test.yaml

  sonar-scan:
    uses: ./.github/workflows/sonar.yaml
    secrets: inherit
    needs: unit-tests
  
  synk-test:
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit
    needs: sonar-scan
    

  buildAndArchive:
    uses: ./.github/workflows/build-artifact.yaml
    needs: synk-test
  
  docker-build:
    uses: ./.github/workflows/docker-build.yaml
    needs: buildAndArchive


  # combined this with build-artifact

  # archive-artifact:
  #  uses: ./.github/workflows/archive-artifact.yaml
 

  