name: Modular CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: ./.github/workflows/test.yaml

  sonar-scan:
    uses: ./.github/workflows/sonar.yaml
    secrets: inherit
  
  synk-test:
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit

  build:
    uses: ./.github/workflows/build-artifact.yaml

  # combined this with build-artifact
  
  # archive-artifact:
  #  uses: ./.github/workflows/archive-artifact.yaml
 

  