name: Deploy Docker Image to EC2

on:
  workflow_call

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Pulling Image......."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:${{ github.sha }}
            echo "remove old container if exists"
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:${{ github.sha }}
            docker ps -a
            echo "Deployment completed with new image built on java 17."