name: Push Docker Image to DockerHub

on:
  workflow_call:

jobs:
  docker-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Download Docker Image Artifact (Optional if image is built locally)
        run: |
          docker images

      - name: Tag Docker Image
        run: |
          docker tag petclinic ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:latest