name: Push Docker Image to DockerHub

on:
  workflow_call:

jobs:
  docker-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Download Docker Image Artifact (Optional if image is built locally)
        run: |
          docker images

      - name: Tag Docker Image
        run: |
          docker tag petclinic:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:${{ github.sha }}


      - name: Update Kubernetes manifest with new image tag
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/onmo-sports:${{ github.sha }}|" kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email ${{ secrets.GITHUB_MAIL }}
          git config --global user.name ${{ secrets.GITHUB_USER }}
          git commit -am "Update image tag to ${GITHUB_SHA}"
          git push