name : docker image build

on:
  workflow_call

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - name: Set Docker Tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t petclinic:${{ env.TAG }} .

      - name: List Docker Images
        run: docker images

