# .github/workflows/eks-deploy.yml
name: Deploy to EKS

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.29'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernates/deployment.yaml
          kubectl apply -f kubernates/service.yaml
      
      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get services
          echo "Deployment to EKS completed successfully."