name: jfrog upload artifact

on:
  workflow_call

jobs:
  jfrog-upload:
    runs-on: self-hosted

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: target

      - name: Set up JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/jf
        
      - name: Configure JFrog CLI
        run: |
          if ! jf config show artifactory-server &> /dev/null; then
            jf config add artifactory-server \
              --artifactory-url=${{ secrets.JF_URL }} \
              --user=${{ secrets.JF_USER }} \
              --apikey=${{ secrets.JF_API_KEY }} \
              --interactive=false
          else
            echo "JFrog config 'artifactory-server' already exists. Skipping."
          fi

      - name: Upload Artifact [jar artifact]
        run: |
          jf rt u "target/*.jar" "onmo-sports-jf-repo/" \
          --build-name=petclinic \
          --build-number=${{ github.run_number }}